### ISSUE TITLE
How can I enable T3A?

### ISSUE THREAD

**Issue by JihwanEom** [maryam089/SDViT#2]
Hi!  Thank you for awesome works :)

I could reproduce the result of paper using baseline_sweep.sh but I want to enable T3A to get maximum score.

Could you explain how to enable this?

Thank you!

**Comment by maryam089** [comment]
Thank you for your interest in our work. To enable T3A, Download the code at this link: [T3A_Code](https://drive.google.com/file/d/1TBQjF_8E25SJvVOsM4FMsDxNO6gTQkBy/view?usp=sharing). The code is almost identical provided at the official repository of [T3A](https://github.com/matsuolab/T3A) with few modifications. Add ERM-ViT algorithm in algorithms.py file. And run the following command as per your dataset choice.                                                                        `python -m domainbed.scripts.unsupervised_adaptation --input_dir=./domainbed/PACS_Output/ERM_ViT/backbone_DeitSmall/ --adapt_algorithm=T3A`. Run collect_results.py to see the output.
