### ISSUE TITLE
ImageNet pretrained T2T checkpoint is corrupted

### ISSUE THREAD

**Issue by JihwanEom** [maryam089/SDViT#3]
Hi, sorry for several requests.

Your release ImageNet pretrained T2T checkpoint (81.5_T2T_ViT_14.pth.tar) is corrupted.
I also tried to find same uncorrupted checkpoint but failed to load.

Could you share working T2T ImageNet pretrained checkpoint?

Thank you!

**Comment by maryam089** [comment]
Please download: [pretrained T2T checkpoint](https://drive.google.com/file/d/1tBWvwThlvQMBCmok-f63a6weWdwJiGr9/view?usp=sharing). [Source](https://github.com/yitu-opensource/T2T-ViT), Model: T2T_ViT_t-14 (Top1 Acc: 81.7, T2T Transformer: Transformer, #params: 21.5M)
